name: CI

on:
  push:
    branches: [ "main", "dev", "dev-*", "ci" ]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  CI:
    runs-on: ${{ matrix.os }}
    # container:
    #   image: ${{ matrix.container-image }}
    #   volumes:
    #     - /usr/local/share/vcpkg:/vcpkg

    env:
      VCPKG_BINARY_SOURCES: "clear" # Disable binary caching, since we cache exports ourselves
      vcpkg_exports: "vcpkg_exports"

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-26.04, ubuntu-26.04-arm, windows-latest, windows-11-arm, macos-latest]
        build_type: [Release]
        include:
          - os: macos-latest
            # cmake_extra_flags: "-D CMAKE_OSX_ARCHITECTURES='arm64;x86_64'"
            vcpkg_triplet: "arm64-osx"
          - os: windows-latest
            bin_ext: ".exe"
            # cmake_extra_flags: "-D CMAKE_MSVC_RUNTIME_LIBRARY='MultiThreaded$<$<CONFIG:Debug>:Debug>'"
            vcpkg_triplet: "x64-windows-static-md"
          - os: windows-11-arm
            bin_ext: ".exe"
            # cmake_extra_flags: "-D CMAKE_MSVC_RUNTIME_LIBRARY='MultiThreaded$<$<CONFIG:Debug>:Debug>'"
            vcpkg_triplet: "arm64-windows-static-md"
          - os: ubuntu-26.04
            vcpkg_triplet: "x64-linux"
            # container-image: "kya8/fedora-dev:latest"
          - os: ubuntu-26.04-arm
            vcpkg_triplet: "arm64-linux"
        #c_compiler: [gcc, clang, cl]

    steps:

    - uses: actions/checkout@v6
      with:
        # required for generating version
        fetch-depth: 0
        fetch-tags: true

    - name: Restore vcpkg exports from cache
      id: cache-restore-exports
      uses: actions/cache/restore@v5
      with:
        path: ${{ env.vcpkg_exports }}
        # Cache invalidation factors: vcpkg triplet, changes to vcpkg.json or vcpkg-configuration.json
        key: vcpkg-export-${{ matrix.vcpkg_triplet }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json') }}

    - name: Set reusable strings
      id: strings
      run: |
        echo "build_dir=${GITHUB_WORKSPACE}/build" >> "$GITHUB_OUTPUT"

    - name: Set up MSVC environment on Windows
      # Required for CMake generators other than MSBuild
      if: ${{ runner.os == 'Windows' }}
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
          arch: ${{ case(runner.arch == 'X64', 'x64', 'amd64_arm64') }}

    - name: Setup the container
      if: ${{ matrix.container-image != '' }}
      run: |
        echo "/vcpkg" >> "$GITHUB_PATH"
        git config --global --add safe.directory "${GITHUB_WORKSPACE}"

    - name: Install and export deps if cache not hit
      if: steps.cache-restore-exports.outputs.cache-hit != 'true'
      run: |
        mkdir -p "${{ env.vcpkg_exports }}"
        vcpkg install --triplet=${{ matrix.vcpkg_triplet }} --host-triplet=${{ matrix.vcpkg_triplet }}
        vcpkg export --triplet=${{ matrix.vcpkg_triplet }} --host-triplet=${{ matrix.vcpkg_triplet }} --raw --output-dir="${{ env.vcpkg_exports }}" --output=deps

    - name: Save cache of vcpkg exports
      if: steps.cache-restore-exports.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: ${{ env.vcpkg_exports }}
        key: ${{ steps.cache-restore-exports.outputs.cache-primary-key }}

    - name: Configure CMake
      run: >
        cmake -G Ninja
        -S "${GITHUB_WORKSPACE}"
        -B '${{ steps.strings.outputs.build_dir }}'
        -D CMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -D CMAKE_TOOLCHAIN_FILE="${vcpkg_exports}/deps/scripts/buildsystems/vcpkg.cmake"
        -D VCPKG_MANIFEST_MODE=0
        -D VCPKG_TARGET_TRIPLET=${{ matrix.vcpkg_triplet }}
        -D VCPKG_HOST_TRIPLET=${{ matrix.vcpkg_triplet }}
        ${{ matrix.cmake_extra_flags }}

    - name: Build and install
      working-directory: ${{ steps.strings.outputs.build_dir }}
      run: |
        cmake --build .
        cpack

    - name: Run tests
      working-directory: ${{ steps.strings.outputs.build_dir }}
      run: ctest -V

    - uses: actions/upload-artifact@v7
      with:
        name: slate-${{ github.sha }}-${{ runner.os }}_${{ runner.arch }}
        path: |
          ${{ steps.strings.outputs.build_dir }}/*.tar.*
        archive: false
